---
title: "Conditions"
output:
  html_document:
    number_sections: yes
    theme: sandstone
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(tidy=TRUE, fig.align='center')
```

```{r, echo=FALSE, include=FALSE}
library(lobstr)
library(pryr)
library(knitr)
library(kableExtra)
library(magrittr)
library(dplyr)
library(tidyverse)
library(rlang)
```

# Conditions
## Introduction
The **condition** system provides a paired set of tools that allow the author of a function to indicate that something unusual is happening, and the user of that function to deal with it. The function author signals conditions with functions like `stop()` (for errors), `warning()` (for warnings), and `message()` (for messages), then the function user can handle them with functions like `tryCatch()` and `withCallingHandlers()`. Understanding the condition system is important because you’ll often need to play both roles: signalling conditions from the functions you create, and handle conditions signalled by the functions you call.

## Signalling conditions
There are three conditions that you can signal in code: errors, warnings, and messages.

* Errors are the most severe; they indicate that there is no way for a function to continue and execution must stop.

* Messages are the mildest; they are way of informing the user that some action has been performed on their behalf.

* Warnings fall somewhat in between, and typically indicate that something has gone wrong but the function has been able to at least partially recover.

There is a final condition that can only be generated interactively: an interrupt, which indicates that the user has “interrupted” execution by pressing Escape, Ctrl + Break, or Ctrl + C (depending on the platform).

```{r, error=TRUE}
stop("This is what an error looks like")
warning("This is what a warning looks like")
message("This is what a message looks like")
```

### Errors
In base R, errors are signalled, or thrown, by `stop()`:
```{r, error=TRUE}
f <- function() g()
g <- function() h()
h <- function() stop("This is an error!")

f()
```

### Warnings
Warnings, signalled by `warning()`, are weaker than errors: they signal that something has gone wrong, but the code has been able to recover and continue. Unlike errors, you can have multiple warnings from a single function call:
```{r, eval=FALSE}
fw <- function() {
  cat("1\n")
  warning("W1")
  cat("2\n")
  warning("W2")
  cat("3\n")
  warning("W3")
}

fw()
```

```
1
2
3
Warning messages:
1: In fw() : W1
2: In fw() : W2
3: In fw() : W3
```

By default, warnings are cached and printed only when control returns to the top level. You can control this behaviour with the warn option:

* To make warnings appear immediately, set options(warn = 1).

* To turn warnings into errors, set * options(warn = 2). This is usually the easiest way to debug a warning, as once it’s an error you can use tools like `traceback()` to find the source.

* Restore the default behaviour with options(warn = 0).

### Messages
`messages()` are displayed immediately and do not have a call. argument:
```{r}
fm <- function() {
  cat("1\n")
  message("M1")
  cat("2\n")
  message("M2")
  cat("3\n")
  message("M3")
}
```

Generally any function that produces a message should have some way to suppress it, like a `quiet = TRUE` argument. It is possible to suppress all messages with `suppressMessages()`.

### Exercises
1. Write a wrapper around `file.remove()` that throws an error if the file to be deleted does not exist.  
**A**:
    ```{r, error=TRUE}
    file_remove <- function(...) {
      if (!suppressWarnings(file.remove(...))) stop ("No such file")
    }
    
    file_remove("nosuchfile.no")
    ```

2. What does the appendLF argument to `message()` do? How is it related to `cat()`?  
**A**: indicates if a new line should be added to messages. `cat()` requires a `\n` for a new line.
    ```{r}
    message("Hello World!", appendLF = TRUE)
    message("Hello World!", appendLF = FALSE)
    message("Hello World\n", appendLF = FALSE)
    message("Hello World!", appendLF = TRUE)
    ```

3. What does `options(error = recover)` do? Why might you use it?  
**A**: When an error occurs, the standard R browser is then invoked from the corresponding environment; the user can type ordinary R language expressions to be evaluated in that environment.

4. What does `options(error = quote(dump.frames(to.file = TRUE)))` do? Why might you use it?  
**A**: Dumps error information to a file. Might be used for post-mortem debugging in non-interactive sessions.

## Ignoring conditions
The simplest way of handling conditions in R is to simply ignore them:

* Ignore errors with `try()`.
* Ignore warnings with `suppressWarnings()`.
* Ignore messages with `suppressMessages()`.

These functions are heavy handed as you can’t use them to suppress a single type of condition that you know about, while allowing everything else to pass through. We’ll come back to that challenge later in the chapter.

`try()` allows execution to continue even after an error has occurred. Normally if you run a function that throws an error, it terminates immediately and doesn’t return a value:

```{r, error=TRUE}
f1 <- function(x) {
  log(x)
  10
}
f1("x")
```

It is possible, but not recommended, to save the result of `try()` and perform different actions based on whether or not the code succeed or failed. 

```{r, error=TRUE}
err <- try(log("a"))
class(err)
cnd <- attributes(err)$condition
conditionCall(cnd)
conditionMessage(cnd)
class(cnd)
names(cnd)
str(cnd)
```

Instead, it is better to use `tryCatch()` or a higher-level helper; you’ll learn about those shortly. A simple, but useful, pattern is to do assignment inside the call: this lets you define a default value to be used if the code does not succeed.

```{r, error=TRUE}
read.csv("possibly-bad-input.csv")

default <- NULL
try(default <- read.csv("possibly-bad-input.csv"), silent = TRUE)
default
```

## Handling conditions
Every condition has default behaviour: errors stop execution and return to the top level, warnings are captured and displayed in aggregate, and messages are immediately displayed. Condition handlers allow us to temporarily override or supplement the default behaviour.

Two functions, `tryCatch()` and `withCallingHandlers()`, allow us to register handlers, functions that take the signalled condition as their single argument. They differ in the type of handlers that they create:

* `tryCatch()` defines exiting handlers; after the condition is handled, control returns to the context where tryCatch() was called. This makes `tryCatch()` most suitable for working with errors and interrupts, as these have to exit anyway.

* `withCallingHandlers()` defines calling handlers; after the condition is captured control returns to the context where the condition was signalled. This makes it most suitable for working with non-error conditions.

### Exiting handlers

```{r}
tryCatch(
  error = function(cnd) 10,  
  stop("This is an error!")
)
```

If no conditions are signalled, or the class of the signalled condition does not match the handler name, the code executes normally:

```{r}
tryCatch(
  error = function(cnd) 10,
  1 + 1
)

tryCatch(
  error = function(cnd) 10,
  {
    message("Hi!")
    1 + 1
  }
)

```

The handlers set up by `tryCatch()` are called **exiting handlers** because after the condition is signalled, control passes to the handler and never returns to the original code, effectively meaning that the code “exits”:

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    message("Here")
    stop("This code is never run!")
  }
)

tryCatch(
  message = function(cnd) conditionMessage(cnd),
  {
    message("Here")
    stop("This code is never run!")
  }
)
```

Note that the code is evaluated in the environment of `tryCatch()`, but the handler code is not, because the handlers are functions. This is important to remember if you’re trying to modify objects in the parent environment.

```{r}
tryCatch(
  message = function(cnd) {print(environment()); print(parent.frame(4)); lobstr::cst()},
  {
    print("Hi")
    print(environment())
    message("Here")
  }
)
```

The handler functions are called with a single argument, the condition object. This value is only moderately useful for the base conditions because they contain relatively little data. It’s more useful when you make your own custom conditions, as you’ll see shortly.

```{r}
tryCatch(
  error = function(cnd) {
    paste0("--", conditionMessage(cnd), "--")
  },
  stop("This is an error")
)
```

Only the first handler is executed:

```{r}
tryCatch(
  error = function(cnd) paste0("--", conditionMessage(cnd), "--"),
  error = function(cnd) print("this is still an error"),
  stop("This is an error")
)

tryCatch(
  error = function(cnd) print("this is still an error"),
  error = function(cnd) paste0("--", conditionMessage(cnd), "--"),
  stop("This is an error")
)
```

`tryCatch()` has one other argument: `finally`. It specifies a block of code (not a function) to run regardless of whether the initial expression succeeds or fails. This can be useful for clean up, like deleting files, or closing connections. This is functionally equivalent to using `on.exit()` (and indeed that’s how it’s implemented) but it can wrap smaller chunks of code than an entire function.

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    print("Hi")
    print(environment())
    message("Here")
  },
  finally = {print(environment()); print("and everywhere")}
)
```

and this...

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    print("Hi")
    print(environment())
    f <- function() on.exit(print("and everywhere"))
    f()
    message("Here")
  }
)
```

and this...

```{r}
tryCatch(
  message = function(cnd) {on.exit(print("and everywhere")); "There"},
  {
    print("Hi")
    print(environment())
    message("Here")
  }
)
```

### Calling handlers
The handlers set up by `tryCatch()` are called exiting handlers, because they cause code to exit once the condition has been caught. By contrast, `withCallingHandler()` sets up calling handlers: code execution continues normally once the handler returns. This tends to make `withCallingHandlers()` a more natural pairing with the non-error conditions.

```{r}
tryCatch(
  message = function(cnd) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)

withCallingHandlers(
  message = function(c) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

More than one handler of the same type can be defined:

```{r}
withCallingHandlers(
  message = function(c) cat("Caught a message!\n"), 
  message = function(c) cat("Caught a message again!\n"),
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

By default, a condition will continue to propogate to parent handlers, all the way up to the default handler (or an exiting handler, if provided):

```{r, tidy=FALSE}
# Bubbles all the way up to default handler which generates the message
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)

# Bubbles up to tryCatch
tryCatch(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

One important side-effect unique to calling handlers is the ability to muffle the signal. To do so, call `invokeRestart("muffleMessage")`. See section on restarts.

There is also the equivalent for warnings:

```{r}
withCallingHandlers(
  warning = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    warning = function(cnd) cat("Level 1\n"),
    warning("Hello", call. = FALSE)
  )
)

# muffles level 2 and default handler which prints the message
withCallingHandlers(
  warning = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    warning = function(cnd) {cat("Level 1\n"); invokeRestart("muffleWarning")},
    warning("Hello", call. = FALSE)
  )
)


# muffles level 2 and default handler which prints the message
withCallingHandlers(
  warning = function(cnd) cat("Level 2\n"),
  suppressWarnings(
    withCallingHandlers(
      warning = function(cnd) {cat("Level 1\n"); invokeRestart("muffleWarning")},
      warning("Hello", call. = FALSE)
    )
  )
)

warning
```

### Exercises
1. Predict the results of evaluating the following code:
    ```{r}
    show_condition <- function(code) {
      tryCatch(
        error = function(cnd) "error",
        warning = function(cnd) "warning",
        message = function(cnd) "message",
        {
          code
          NULL
        }
      )
    }
    
    show_condition(stop("!")) # "error"
    show_condition(10) # NULL
    show_condition(warning("?!")) # "warning"
    show_condition({
      10
      message("?")
      warning("?!") # "message"
    })
    ```
**A**: "error", `NULL`, "warning", "message"

2. Explain the results of running this code:
    ```{r}
    withCallingHandlers(
      message = function(cnd) message("b"),
      withCallingHandlers(
        message = function(cnd) message("a"),
        message("c")
      )
    )
    ```
**A**: 
Let the innermost hander be 1, and the outer handler 2. Now remember that `message()` causes `signalConditon()` to be called followed by the default handler which prints the message to the screen. Crucially, `signalConditon()` will try all handlers defined in the call stack. Hence:  
    ```{r, eval=FALSE, results='asis', tidy=FALSE}
    message("c")
    |
    |------handler1: message("a")
    |                |
    |                |------handler2: message("b")
    |                |                |     
    |                |                |------print("b")
    |                |  
    |                |------print("a")  
    |  
    |------handler2: message("b")
    |                |
    |                |------print("b")
    |
    |------print("c")
    ```

3. Read the source code for `catch_cnd()` and explain how it works.  
    ```{r}
    catch_cnd
    ```
**A**: Captures any condition (message, warning, error or interrupt) and returns the condition (`identity()` function) which is printed to the screen. If there is no condition the expression is evaluted and `NULL` is returned.

4. How could you rewrite `show_condition()` to use a single handler?  
**A**:
    ```{r}
    show_condition <- function(code) {
      tryCatch(
        condition = conditionMessage,
        {
          code
          NULL
        }
      )
    }

    show_condition(stop("!")) 
    show_condition(10) 
    show_condition(warning("?!")) 
    show_condition({
      10
      message("?")
      warning("?!") 
    })
    ```

## Other things to note
Note that a condition is a message, warning, error or interrupt. Note the classes and restarts associated with each.
```{r, error=TRUE}
withCallingHandlers(
  condition = function(cnd) {print(class(cnd)); print(computeRestarts())},
  {
    message("%")
    warning("?", call. = FALSE)
    stop("!", call. = FALSE)
  }
)
```

And also for interrupts:

```{r, eval=FALSE}
withCallingHandlers(
  condition = function(cnd) {print(class(cnd)); print(computeRestarts())},
  {
    print("Try to escape")
    Sys.sleep(1) # press esc key
  }
)
```
```
# [1] "Try to escape"
# [1] "interrupt" "condition"
# [[1]]
# <restart: resume >

# [[2]]
# <restart: abort >
```

So `simpleMessage`, `simpleWarning` and `simpleError` can be used as handlers to. E.g.:

```{r}
withCallingHandlers(
  simpleMessage = function(cnd) print("is it simple?"),
  message("yes")
)
```

`signalCondition()` can be used to raise a condition. It takes a condition object as an argument (or a chaaracter string - see later):

```{r, eval=FALSE}
withCallingHandlers(
  message = function(cnd) print("is it simple?"),
  signalCondition(simpleMessage("yes")) # no default handler which prints message to screen, returns NULL
)

# [1] "is it simple?"

# NULL
```

``` {r}
withCallingHandlers(
   message = function(cnd) {print("is it simple?"); invokeRestart("muffleMessage")},
   message("yes") # return NULL but is invisible
)
```

Interrupts can be suspended while evaluating an expression using `suspendInterrupts`. Subexpression can be evaluated with interrupts enabled using `allowInterrupt`s. These functions can be used to make sure cleanup handlers cannot be interrupted.

```{r, eval=FALSE}
withCallingHandlers(
  condition = function(cnd) "interrupted",
  {
    suspendInterrupts(
      {
        print("Try to escape")
        Sys.sleep(5) # press esc key - won't interrupt
        allowInterrupts(
          {
            print("Try to escape now")
            Sys.sleep(5) # press esc key - will interrupt, but will not bubble up to handler
          }
        )
      }
    )
  }
)
```

## Condition objects
Built-in conditions are lists with two elements:

* `message`, a length-1 character vector containing the text display to a user. To extract the message, use `conditionMessage(cnd)`.
* `call`, the call which triggered the condition. To extract it, use `conditionCall(cnd)`.

```{r}
tryCatch(
  error = function(cnd) {print(conditionMessage(cnd)); print(conditionCall(cnd))},
  y <- log("x")
)
```

Conditions can be created using the following functions:

```{r}
str(simpleMessage("yes"))
str(simpleWarning("yes"))
str(simpleError("yes"))
str(simpleCondition("yes"))

simpleMessage
simpleWarning
simpleError
simpleCondition
```

Notice that every one has the class `condition`. Also notice that `simpleCondition` is not captured by the `message`, `warning` and `error` handlers (and also `interrupt`).

```{r, tidy=FALSE}
withCallingHandlers(
  message = function(cnd) print("is it simple?"), # not called
  signalCondition(simpleCondition("yes"))
)

withCallingHandlers(
  condition = function(cnd) print("is it simple?"), # called
  signalCondition(simpleCondition("yes"))
)
```

Note that if the `signalCondition()` argument is not a condition, then a `simpleCondition` is created.

```{r}
withCallingHandlers(
  condition = function(cnd) {print(conditionMessage(cnd)); print(class(cnd))},
  signalCondition("yes") 
)

signalCondition
```

### Custom conditions
R has a powerful, but little used feature: the ability to create custom conditions that can contain additional metadata.

```{r, tidy=FALSE}
stop_custom <- function(.subclass, message, call = NULL, ...) {
  err <- structure(
    list(
      message = message,
      call = call,
      ...
    ),
    class = c(.subclass, "error", "condition")
  )
  stop(err)
}

err <- tryCatch(
  condition = identity, # same as condition = function(cnd) cnd
  stop_custom("error_new", "This is a custom error", x = 10)
)

class(err)
err$x

tryCatch(
  error_new = function(cnd) {print(conditionMessage(cnd)); print(cnd$x)},
  stop_custom("error_new", "This is a custom error", x = 10)
)

tryCatch(
  condition = function(cnd) "hi",
  error_new = function(cnd) {print(conditionMessage(cnd)); print(cnd$x)},
  stop_custom("error_new", "This is a custom error", x = 10)
)
```

## Restarts
One of R’s great features is its condition system. It serves a similar purpose to the exception handling systems in Java, Python, and C++ but is more flexible. In fact, its flexibility extends beyond error handling–conditions are more general than exceptions in that a condition can represent any occurrence during a program’s execution that may be of interest to code at different levels on the call stack. For example, conditions can be used to emit warnings without disrupting execution of the code that emits the warning while allowing code higher on the call stack to control whether the warning message is printed.

The condition system is more flexible than exception systems because instead of providing a two-part division between the code that signals an error and the code that handles it, the condition system splits the responsibilities into three parts–signaling a *condition*, *handling* it, and *restarting*.

You’ll see how you could use the condition system to allow a low-level function to detect a problem while parsing a log file and signal an error, to allow mid-level code to provide several possible ways of recovering from such an error, and to allow code at the highest level of the application to define a policy for choosing which recovery strategy to use.

In most languages, errors are handled by returning from a failing function and giving the caller the choice of either recovering or failing itself. Some languages use the normal function return mechanism, while languages with exceptions return control by *throwing* or *raising* an exception. Exceptions are a vast improvement over using normal function returns, but both schemes suffer from a common flaw: while searching for a function that can recover, the stack unwinds, which means code that might recover has to do so without the context of what the lower-level code was trying to do when the error actually occurred.

Consider the hypothetical call chain of `high`, `medium`, `low`. If `low` fails and `medium` can’t recover, the ball is in `high`’s court. For `high` to handle the error, it must either do its job without any help from `medium` or somehow change things so calling `medium` will work and call it again. The first option is theoretically clean but implies a lot of extra code–a whole extra implementation of whatever it was `medium` was supposed to do. And the further the stack unwinds, the more work that needs to be redone. The second option–patching things up and retrying–is tricky; for `high` to be able to change the state of the world so a second call into `medium` won’t end up causing an error in `low`, it’d need an unseemly knowledge of the inner workings of both `medium` and `low`, contrary to the notion that each function is a black box.

### The R way
R’s error handling system gives you a way out of this conundrum by letting you separate the code that actually recovers from an error from the code that decides how to recover. Thus, you can put recovery code in low-level functions without committing to actually using any particular recovery strategy, leaving that decision to code in high-level functions.

To get a sense of how this works, let’s suppose you’re writing an application that reads some sort of textual log file, such as a Web server’s log. Somewhere in your application you’ll have a function to parse the individual log entries. Let’s assume you’ll write a function, parse_log_entry(), that will be passed a string containing the text of a single log entry and that is supposed to return a `log_entry()` object representing the entry. This function will be called from a function, `parse_log_file()`, that reads a complete log file and returns a list of objects representing all the entries in the file.

To keep things simple, the `parse_log_entry()` function will not be required to parse incorrectly formatted entries. It will, however, be able to detect when its input is malformed. But what should it do when it detects bad input? In C you’d return a special value to indicate there was a problem. In Java or Python you’d throw or raise an exception. In R, you signal a condition.

### Conditions
A *condition* is an S3 object whose class indicates the general nature of the condition and whose instance data carries information about the details of the particular circumstances that lead to the condition being signaled.3 In this hypothetical log analysis program, you might define a condition class, malformed_log_entry_error, that parse_log_entry() will signal if it’s given data it can’t parse.

Conditional classes are regular S3 classes, built up from a list with components message and call. There is no built in function to generate a new object of class condition, but we can add one:

```{r, eval=FALSE}
condition <- function(subclass, message, call = sys.call(-1), ...) {
  structure(
    class = c(subclass, "condition"),
    list(message = message, call = call, ...)
  )
}
```

When using the condition system for error handling, you should define your conditions as subclasses of error, a subclass of condition. Thus, you might define malformed_log_entry_error, with a slot to hold the argument that was passed to `parse_log_entry()`, like this:

```{r, eval=FALSE}
malformed_log_entry_error <- function(text) {
  msg <- paste0("Malformed log entry: ", text)
  condition(c("malformed_log_entry_error", "error"),
    message = msg, 
    text = text
  )
}
```

In `parse_log_entry()` you’ll signal a `malformed_log_entry_error` if you can’t parse the log entry. You signal errors with the function `stop()`. `stop()` is normally just called with a string, the error message, but you can also call it with a condition object. Thus, you could write `parse_log_entry()` like this, eliding the details of actually parsing a log entry:

```{r, eval=FALSE}
parse_log_entry <- function(text) {
  if (!well_formed_log_entry(text)) {
    stop(malformed_log_entry_error(text))
  }
  
  new_log_entry(text)
}
```

Implement `parse_log_file()` so it establishes a restart. In general, a restart name should describe the action the restart takes. In `parse_log_file()`, you can call the restart `skip_log_entry` since that’s what it does:

```{r, eval=FALSE}
parse_log_file <- function(file) {
  lines <- readLines(file)
  
  lapply(lines, function(text) {
    withRestarts(
      parse_log_entry(text),
      skip_log_entry = function(e) NULL
    )
  })
}
```

If you invoke this version of `parse_log_file()` on a log file containing corrupted entries, it won’t handle the error directly; you’ll end up in the debugger. However, there among the various restarts listed by `findRestarts()` will be one called `skip_log_entry`, which, if you choose it, will cause `parse_log_file()` to continue on its way as before. To avoid ending up in the debugger, you can establish a condition handler that invokes the `skip_log_entry` restart automatically.

The advantage of establishing a restart rather than having `parse_log_file()` handle the error directly is it makes `parse_log_file()` usable in more situations. The higher-level code that invokes `parse_log_file()` doesn’t have to invoke the `skip_log_entry` restart. It can choose to handle the error at a higher level. Or, as I’ll show in the next section, you can add restarts to `parse_log_entry()` to provide other recovery strategies, and then condition handlers can choose which strategy they want to use.

You need to see how to set up a condition handler that will invoke the `skip_log_entry` restart. You can set up the handler anywhere in the chain of calls leading to `parse_log_file()`. This may be quite high up in your application, not necessarily in `parse_log_file()`’s direct caller. For instance, suppose the main entry point to your application is a function, `log_analyzer()`, that finds a bunch of logs and analyzes them with the function `analyze_log()`, which eventually leads to a call to `parse_log_file()`. Without any error handling, it might look like this:

```{r, eval=FALSE}
log_analyzer <- function() {
  logs <- find_all_logs()
  lapply(logs, analyze_log)
}
```

The job of `analyze_log()` is to call, directly or indirectly, `parse_log_file()` and then do something with the list of log entries returned. An extremely simple version might look like this:

```{r, eval=FALSE}
analyze_log <- function(log) {
  entries <- parse_log_file(log)
  lapply(entries, analyze_entry)
}
```

where the function `analyze_entry()` is presumably responsible for extracting whatever information you care about from each log entry and stashing it away somewhere.

So you can add a handler to log_analyzer() that will invoke the skip_log_entry restart established in parse_log_file() like this:

```{r, eval=FALSE}
log_analyzer <- function() {
  logs <- find_all_logs()
  
  withCallingHandlers(
    malformed_log_entry_error = function(e) invokeRestart("skip_log_entry"),
    lapply(logs, analyze_log)
  )
}
```

In this `withCallingHandlers()`, the handler function is an anonymous function that invokes the restart `skip_log_entry`. You could also define a named function that does the same thing and bind it instead. In fact, a common practice when defining a restart is to define a function, with the same name and taking a single argument, the condition, that invokes the eponymous restart. Such functions are called *restart functions*. You could define a restart function for `skip_log_entry` like this:

```{r, eval=FALSE}
skip_log_entry <- function() invokeRestart("skip_log_entry")
```

Then you could change the definition of log_analyzer() to this:

```{r, eval=FALSE}
log_analyzer <- function() {
  logs <- find_all_logs()
  
  withCallingHandlers(
    malformed_log_entry_error = skip_log_entry,
    lapply(logs, analyze_log)
  )
}
```

As written, the `skip_log_entry` restart function assumes that a `skip_log_entry` restart has been established. If a `malformed_log_entry_error` is ever signaled by code called from `log_analyzer()` without a `skip_log_entry` having been established, the call to `invokeRestart()` will signal an error when it fails to find the `skip_log_entry` restart. If you want to allow for the possibility that a `malformed_log_entry_error` might be signaled from code that doesn’t have a `skip_log_entry` restart established, you could change the `skip_log_entry` function to this:

```{r, eval=FALSE}
skip_log_entry <- function() {
  r <- findRestart("skip_log_entry") 
  if (is.null(r)) return()
  
  invokeRestart(r)
}
```

`findRestart` looks for a restart with a given name and returns an object representing the restart if the restart is found and `NUL`L if not. You can invoke the restart by passing the restart object to `invokeRestart()`. Thus, when `skip_log_entry` is bound with `withCallingHandlers()`, it will handle the condition by invoking the `skip_log_entry` restart if one is available and otherwise will return normally, giving other condition handlers, bound higher on the stack, a chance to handle the condition.

### Providing multiple restarts
Since restarts must be explicitly invoked to have any effect, you can define multiple restarts, each providing a different recovery strategy. As I mentioned earlier, not all log-parsing applications will necessarily want to skip malformed entries. Some applications might want `parse_log_file()` to include a special kind of object representing malformed entries in the list of log-entry objects; other applications may have some way to repair a malformed entry and may want a way to pass the fixed entry back to `parse_log_entry()`.

To allow more complex recovery protocols, restarts can take arbitrary arguments, which are passed in the call to `invokeRestart()`. You can provide support for both the recovery strategies I just mentioned by adding two restarts to `parse_log_entry()`, each of which takes a single argument. One simply returns the value it’s passed as the return value of `parse_log_entry()`, while the other tries to parse its argument in the place of the original log entry.

```{r, eval=FALSE}
parse_log_entry <- function(text) {
  if (well_formed_log_entry(text)) {
    return(new_log_entry(text))
  }
  
  withRestarts(
    stop(malformed_log_entry_error(text)),
    use_value = function(x) x,
    reparse_entry = function(fixed_text) parse_log_entry(fixed_text)
  )
}
```

The name `use_value()` is a standard name for this kind of restart. You can define a restart function for `use_value` similar to the `skip_log_entry` function you just defined.

```{r, eval=FALSE}
use_value <- function(x) invokeRestart("use_value", x)
```

So, if you wanted to change the policy on malformed entries to one that created an instance of `malformed_log_entry`, you could change `log_analyzer()` to this (assuming the existence of a `malformed_log_entry constructor` with a `text` parameter):

```{r, eval=FALSE}
log_analyzer <- function() {
  logs <- find_all_logs()
  
  withCallingHandlers(
    malformed_log_entry_error = function(text) {
      use_value(malformed_log_entry(text))
    },
    lapply(logs, analyze_log)
  )
}
```

### Structure of restart objects
```{r, error=TRUE}
withCallingHandlers(
  condition = function(cnd) {print(class(cnd)); print(str(computeRestarts()))},
  message("%")
)

withCallingHandlers(
  condition = function(cnd) {print(class(cnd)); print(str(computeRestarts()))},
  warning("?", call. = FALSE)
)

withCallingHandlers(
  condition = function(cnd) {print(class(cnd)); print(str(computeRestarts()))},
  stop("!", call. = FALSE)
)
```




### Other notes

```{r}
# muffles level 2 and default handler which prints the message
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
      message = function(cnd) {cat("Level 1\n"); invokeRestart("muffleMessage")},
      message("Hello")
  )
)

# muffles default handler which prints the message
withCallingHandlers(
  message = function(cnd) {cat("Level 2\n"); invokeRestart("muffleMessage")},
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

The same effect can be acheived with `suppressMessages()`:

```{r}
# muffles level 2 and default handler which prints the message
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  suppressMessages(
    withCallingHandlers(
     message = function(cnd) cat("Level 1\n"),
     message("Hello")
    )
  )
)


# muffles default handler which prints the message
suppressMessages(
  withCallingHandlers(
    message = function(cnd) cat("Level 2\n"),
    withCallingHandlers(
      message = function(cnd) cat("Level 1\n"),
      message("Hello")
    )
  )
)
```

Note that `supressMessages()` is essentially a call to `invokeRestart("muffleMessage")`.

```{r}
suppressMessages
```

How does this work? Look at the code for `message()`:

```{r}
message
```

Note this bit of code:

```
defaultHandler <- function(c) {
    cat(conditionMessage(c), file = stderr(), sep = "")
}
withRestarts({
    signalCondition(cond)
    defaultHandler(cond)
}, muffleMessage = function() NULL)
```

If a condition is signaled and the applicable handler is a calling handler, then the handler is called by `signalCondition(cond)` in the context where the condition was signaled but with the available handlers restricted to those below the handler called in the handler stack. If the handler returns, then the next handler is tried; once the last handler has been tried, signalCondition returns `NULL`.

What this means is that the call to `signalCondition()` in `withRestarts()` will call all available handlers in the call stack. However, when `invokeRestart("muffleMessage")` is called in a handler then execution is returned to `muffleMessage = function() NULL`. This also means that the function `defaultHandler(cond)` is not called, which would have printed the message to the screen.









https://cran.r-project.org/web/packages/tryCatchLog/vignettes/tryCatchLog-intro.html
http://www.win-vector.com/blog/2012/10/error-handling-in-r/




debugger
browser
traceback
