---
title: "Conditions"
output:
  html_document:
    number_sections: yes
    theme: sandstone
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(tidy=TRUE, fig.align='center')
```

```{r, echo=FALSE, include=FALSE}
library(lobstr)
library(pryr)
library(knitr)
library(kableExtra)
library(magrittr)
library(dplyr)
library(tidyverse)
library(rlang)
```

# Conditions
## Introduction
The **condition** system provides a paired set of tools that allow the author of a function to indicate that something unusual is happening, and the user of that function to deal with it. The function author signals conditions with functions like `stop()` (for errors), `warning()` (for warnings), and `message()` (for messages), then the function user can handle them with functions like `tryCatch()` and `withCallingHandlers()`. Understanding the condition system is important because you’ll often need to play both roles: signalling conditions from the functions you create, and handle conditions signalled by the functions you call.

## Signalling conditions
There are three conditions that you can signal in code: errors, warnings, and messages.

* Errors are the most severe; they indicate that there is no way for a function to continue and execution must stop.

* Messages are the mildest; they are way of informing the user that some action has been performed on their behalf.

* Warnings fall somewhat in between, and typically indicate that something has gone wrong but the function has been able to at least partially recover.

There is a final condition that can only be generated interactively: an interrupt, which indicates that the user has “interrupted” execution by pressing Escape, Ctrl + Break, or Ctrl + C (depending on the platform).

```{r, error=TRUE}
stop("This is what an error looks like")
warning("This is what a warning looks like")
message("This is what a message looks like")
```

### Errors
In base R, errors are signalled, or thrown, by `stop()`:
```{r, error=TRUE}
f <- function() g()
g <- function() h()
h <- function() stop("This is an error!")

f()
```

### Warnings
Warnings, signalled by `warning()`, are weaker than errors: they signal that something has gone wrong, but the code has been able to recover and continue. Unlike errors, you can have multiple warnings from a single function call:
```{r, eval=FALSE}
fw <- function() {
  cat("1\n")
  warning("W1")
  cat("2\n")
  warning("W2")
  cat("3\n")
  warning("W3")
}

fw()
```

```
1
2
3
Warning messages:
1: In fw() : W1
2: In fw() : W2
3: In fw() : W3
```

By default, warnings are cached and printed only when control returns to the top level. You can control this behaviour with the warn option:

* To make warnings appear immediately, set options(warn = 1).

* To turn warnings into errors, set * options(warn = 2). This is usually the easiest way to debug a warning, as once it’s an error you can use tools like `traceback()` to find the source.

* Restore the default behaviour with options(warn = 0).

### Messages
`messages()` are displayed immediately and do not have a call. argument:
```{r}
fm <- function() {
  cat("1\n")
  message("M1")
  cat("2\n")
  message("M2")
  cat("3\n")
  message("M3")
}
```

Generally any function that produces a message should have some way to suppress it, like a `quiet = TRUE` argument. It is possible to suppress all messages with `suppressMessages()`.

### Exercises
1. Write a wrapper around `file.remove()` that throws an error if the file to be deleted does not exist.  
**A**:
    ```{r, error=TRUE}
    file_remove <- function(...) {
      if (!suppressWarnings(file.remove(...))) stop ("No such file")
    }
    
    file_remove("nosuchfile.no")
    ```

2. What does the appendLF argument to `message()` do? How is it related to `cat()`?  
**A**: indicates if a new line should be added to messages. `cat()` requires a `\n` for a new line.
    ```{r}
    message("Hello World!", appendLF = TRUE)
    message("Hello World!", appendLF = FALSE)
    message("Hello World\n", appendLF = FALSE)
    message("Hello World!", appendLF = TRUE)
    ```

3. What does `options(error = recover)` do? Why might you use it?  
**A**: When an error occurs, the standard R browser is then invoked from the corresponding environment; the user can type ordinary R language expressions to be evaluated in that environment.

4. What does `options(error = quote(dump.frames(to.file = TRUE)))` do? Why might you use it?  
**A**: Dumps error information to a file. Might be used for post-mortem debugging in non-interactive sessions.

## Ignoring conditions
The simplest way of handling conditions in R is to simply ignore them:

* Ignore errors with `try()`.
* Ignore warnings with `suppressWarnings()`.
* Ignore messages with `suppressMessages()`.

These functions are heavy handed as you can’t use them to suppress a single type of condition that you know about, while allowing everything else to pass through. We’ll come back to that challenge later in the chapter.

`try()` allows execution to continue even after an error has occurred. Normally if you run a function that throws an error, it terminates immediately and doesn’t return a value:

```{r, error=TRUE}
f1 <- function(x) {
  log(x)
  10
}
f1("x")
```

It is possible, but not recommended, to save the result of `try()` and perform different actions based on whether or not the code succeed or failed. 

```{r, error=TRUE}
err <- try(log("a"))
class(err)
cnd <- attributes(err)$condition
conditionCall(cnd)
conditionMessage(cnd)
class(cnd)
names(cnd)
str(cnd)
```

Instead, it is better to use `tryCatch()` or a higher-level helper; you’ll learn about those shortly. A simple, but useful, pattern is to do assignment inside the call: this lets you define a default value to be used if the code does not succeed.

```{r, error=TRUE}
read.csv("possibly-bad-input.csv")

default <- NULL
try(default <- read.csv("possibly-bad-input.csv"), silent = TRUE)
default
```

## Handling conditions
Every condition has default behaviour: errors stop execution and return to the top level, warnings are captured and displayed in aggregate, and messages are immediately displayed. Condition handlers allow us to temporarily override or supplement the default behaviour.

Two functions, `tryCatch()` and `withCallingHandlers()`, allow us to register handlers, functions that take the signalled condition as their single argument. They differ in the type of handlers that they create:

* `tryCatch()` defines exiting handlers; after the condition is handled, control returns to the context where tryCatch() was called. This makes `tryCatch()` most suitable for working with errors and interrupts, as these have to exit anyway.

* `withCallingHandlers()` defines calling handlers; after the condition is captured control returns to the context where the condition was signalled. This makes it most suitable for working with non-error conditions.

### Exiting handlers

```{r}
tryCatch(
  error = function(cnd) 10,  
  stop("This is an error!")
)
```

If no conditions are signalled, or the class of the signalled condition does not match the handler name, the code executes normally:

```{r}
tryCatch(
  error = function(cnd) 10,
  1 + 1
)

tryCatch(
  error = function(cnd) 10,
  {
    message("Hi!")
    1 + 1
  }
)

```

The handlers set up by `tryCatch()` are called **exiting handlers** because after the condition is signalled, control passes to the handler and never returns to the original code, effectively meaning that the code “exits”:

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    message("Here")
    stop("This code is never run!")
  }
)

tryCatch(
  message = function(cnd) conditionMessage(cnd),
  {
    message("Here")
    stop("This code is never run!")
  }
)
```

Note that the code is evaluated in the environment of `tryCatch()`, but the handler code is not, because the handlers are functions. This is important to remember if you’re trying to modify objects in the parent environment.

```{r}
tryCatch(
  message = function(cnd) {print(environment()); print(parent.frame(4)); lobstr::cst()},
  {
    print("Hi")
    print(environment())
    message("Here")
  }
)
```

The handler functions are called with a single argument, the condition object. This value is only moderately useful for the base conditions because they contain relatively little data. It’s more useful when you make your own custom conditions, as you’ll see shortly.

```{r}
tryCatch(
  error = function(cnd) {
    paste0("--", conditionMessage(cnd), "--")
  },
  stop("This is an error")
)
```

`tryCatch()` has one other argument: `finally`. It specifies a block of code (not a function) to run regardless of whether the initial expression succeeds or fails. This can be useful for clean up, like deleting files, or closing connections. This is functionally equivalent to using `on.exit()` (and indeed that’s how it’s implemented) but it can wrap smaller chunks of code than an entire function.

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    print("Hi")
    print(environment())
    message("Here")
  },
  finally = {print(environment()); print("and everywhere")}
)
```

and this...

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    print("Hi")
    print(environment())
    f <- function() on.exit(print("and everywhere"))
    f()
    message("Here")
  }
)
```

and this...

```{r}
tryCatch(
  message = function(cnd) {on.exit(print("and everywhere")); "There"},
  {
    print("Hi")
    print(environment())
    message("Here")
  }
)
```

### Calling handlers
The handlers set up by `tryCatch()` are called exiting handlers, because they cause code to exit once the condition has been caught. By contrast, `withCallingHandler()` sets up calling handlers: code execution continues normally once the handler returns. This tends to make `withCallingHandlers()` a more natural pairing with the non-error conditions.

```{r}
tryCatch(
  message = function(cnd) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)

withCallingHandlers(
  message = function(c) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

One important side-effect unique to calling handlers is the ability to muffle the signal. By default, a condition will continue to propogate to parent handlers, all the way up to the default handler (or an exiting handler, if provided):

```{r, tidy=FALSE}
# Bubbles all the way up to default handler which generates the message
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)

# Bubbles up to tryCatch
tryCatch(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```






https://cran.r-project.org/web/packages/tryCatchLog/vignettes/tryCatchLog-intro.html
http://www.win-vector.com/blog/2012/10/error-handling-in-r/



signalConditon
q or quit
getermessage
debugger
browser
interrupt
muffleWarning
muffleMessage
invokeRestart
traceback
